# Data
train_json: /kaggle/working/Object-Detection/PyTorch-SSD/datasets/coco/train.json
val_json: /kaggle/working/Object-Detection/PyTorch-SSD/datasets/coco/valid.json
test_json: /kaggle/working/Object-Detection/PyTorch-SSD/datasets/coco/test.json
class_names: [ball, goalkeeper, player, referee]
recall_steps: 101
image_mean: [123., 117., 104.]
image_stddev: [1., 1, 1.]

# Model
model: SSD
backbone:
  name: VGG16
  num_stages: 6
input_size: 300
anchor_scales: [0.07, 0.15, 0.3375, 0.525, 0.7125, 0.9]
anchor_aspect_ratios: [[1, 2], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2], [1, 2]]

# Training
batch_size: 32
epochs: 20
optim:
  name: SGD
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  name: MultiStepLR
  milestones: [90, 110]
  gamma: 0.1
